spring.application.name=archimedes
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.port=8082
logging.level.web=DEBUG
logging.level.templates=DEBUG
spring.web.resources.static-locations=classpath:/templates/
spring.mvc.static-path-pattern=/**